Migrate from Oracle Linux 9
EuroLinux/eurolinux-migration-scripts pull request #45
Opened 2022-07-13 13:12 UTC by aronowski

2022-07-13 14:27 UTC, aronowski commented on migrate2eurolinux.sh
> +  if ! yum -y distro-sync --skip-broken ; then
[f63225d](https://github.com/EuroLinux/eurolinux-migration-scripts/pull/45/commits/f63225d8b37edcf566f3c010f083770a60d3b9c0)

2022-07-14 14:26 UTC, jaromaz requested changes

2022-07-14 14:26 UTC, jaromaz commented on migrate2eurolinux.sh
> +        yum remove -y --skip-broken python3-hwdata rhnlib python3-rhnlib python3-rhn-client-tools rhn-client-tools
zostało --skip-broken?

2022-07-14 14:26 UTC, jaromaz commented on migrate2eurolinux.sh
> +  if ! yum -y distro-sync --skip-broken ; then
tu też?

2022-07-14 14:27 UTC, jaromaz approved these changes

2022-07-14 14:27 UTC, merged